feat(SI-6894): Structural patterns
NKom-17/surf-flutter-app-template pull request #23
Opened 2023-11-22 06:41 UTC by NKom-17

2023-11-22 13:32 UTC, maxim-sysoev commented on lib/features/photos/domain/mappers/photos_mapper.dart
> +}
для этого лучше сделать отедльный маппер данных из БД в домаин

2023-11-22 13:32 UTC, maxim-sysoev commented on lib/features/photos/domain/repositories/cached_photos_repository.dart
Похоже наше видение задачи разошлось, поэтому давай опишу в формате ТЗ.

При открытии экрана делается первый запрос для получения списка:
- если ответ совпадает с тем, что хранится в БД - получаем все данные из БД
- если ответ не совпадает – очищаем хранилище и записываем пришедший ответ как единственный

Следующие запросы выполняются по такой схеме:
- если в БД нет данных для запроса - он выполняется
- если в БД есть данные - они возвращаются как ответ сервера

2023-11-23 06:32 UTC, maxim-sysoev requested changes

2023-11-23 06:32 UTC, maxim-sysoev commented on lib/features/photos/domain/mappers/cached_photos_mapper.dart
Лучше сделать отдельный класс как этот
```
/// Маппер сущности [UserSessionEntity].
class UserSessionEntityMapper {
  const UserSessionEntityMapper._();

  /// Из [UserSessionResponseDto] в [UserSessionEntity].
  static UserSessionEntity fromDto(UserSessionResponseDto dto) =>
      UserSessionEntity(
        accessToken: dto.accessToken,
        refreshToken: dto.refreshToken,
      );
}
```

2023-11-23 06:32 UTC, maxim-sysoev commented on lib/features/photos/domain/repositories/cached_photos_repository.dart
> +  }
Это лучше вынести в отдельный репозиторий для взаимоействия с БД.
Сейчас нарушается принцип единственности ответсвенности: класс и репозиторий для взаимодействия с БД, и прокси

2023-11-23 06:32 UTC, maxim-sysoev commented on lib/features/photos/domain/repositories/cached_photos_repository.dart
> +  Future<List<PhotosDTO>> loadingPage(int page) async {
раньше пропустил, из репозитория должен возвращаться entity,  не dto. Репозиторий инкапсулирует логику по получению и подготовке данных к использованию в логике приложения

2023-11-23 06:32 UTC, maxim-sysoev commented on lib/features/photos/domain/repositories/cached_photos_repository.dart
> +      } else {
Это не проверка на то, что ответы совпадают, в ТЗ явно указано, что они должны совпадать.

2023-11-23 06:32 UTC, maxim-sysoev commented on lib/features/photos/domain/repositories/cached_photos_repository.dart
> +        return Future.value(firstPageCachedPhotosDB);
нет смысла добавлять `Future.value`, метод и так асинхронный.

нет смысла получать данные из БД, актуальный список уже есть выше

2023-11-23 06:32 UTC, maxim-sysoev commented on lib/features/photos/domain/repositories/cached_photos_repository.dart
> +          cachedPhotosFromDB.where(response.contains).map((element) => element.toDTO()).toList();
кажется получение всех данных тут излишне, лучше сделать ограничение на количество и начальное положение. Вызывать метод только кода он понадобится.
Если в кэше будет много данных – результат может подгрузить телефон и появятся лаги

2023-11-23 06:32 UTC, maxim-sysoev commented on lib/features/photos/domain/repositories/cached_photos_repository.dart
> +        );
нет смысла использовать `Future.value`

2023-11-23 06:32 UTC, maxim-sysoev commented on lib/features/photos/domain/repositories/cached_photos_repository.dart
> +        return Future.value(newPagePhotosDTOFromDB);
Незачем получать заново данные, актуальные уже получены с сервера

2023-11-23 06:32 UTC, maxim-sysoev commented on lib/features/photos/domain/repositories/cached_photos_repository.dart
> +      if (cachedPhotosFromDB.length >= page * 10) {
Для проверки доступного количества элементов в БД лучше сделать отдельный запрос для получения этого количества, а не получать все данные с БД и считать их. Сейчас лишняя нагрузка выходит.

2023-11-23 08:24 UTC, NKom-17 commented on lib/features/photos/domain/repositories/cached_photos_repository.dart
> +      } else {
я выше проверяю совпадение
final firstPageFromDB = cachedPhotosFromDB.where(response.contains).toList();
а дальше проверяю: если все фото совпали, то беру их из БД, а если нет, то очищаю БД и вставляю новые данные

2023-11-23 10:08 UTC, NKom-17 commented on lib/features/photos/domain/repositories/cached_photos_repository.dart
> +      if (cachedPhotosFromDB.length >= page * 10) {
не очень понял как нужно сделать
Если я создам метод который считает и возвращает количество элементов в БД, то мне все равно нужно это значение будет сравнить с количеством элементов, которые нужно отобразить на экране

2023-11-23 11:59 UTC, maxim-sysoev commented on lib/features/photos/domain/repositories/cached_photos_repository.dart
> +        .sublist(fromIndex, count != null ? fromIndex + count : null)
тут всё ещё получение всей таблицы, лучше это отрегулировать через `offest` и `limit` в запросе к БД

2023-11-23 11:59 UTC, maxim-sysoev commented on lib/features/photos/domain/repositories/photos_repository.dart
> +      ));
можно сделать таким образом:
```dart
return models.map((data) => PhotosDTO.fromJson(data as Map<String, dynamic>))
  .map(PhotosMapper.fromDTO)
  .toList()
```
так выглядит более читаемо и понятно что происходит

2023-11-23 12:47 UTC, maxim-sysoev approved these changes

2023-11-23 12:48 UTC, merged