Si 6192 api layer development
NKom-17/surf-flutter-app-template pull request #5
Opened 2023-10-24 13:19 UTC by NKom-17

## Related tasks

## Dependence on other Pull Requests (optional)

## Background (optional)

## Changes

## Troubles (optional)

## Note (optional)

## Checklist for self-check
- [ ] Commits and PRs have been filed according to [the rules on the project](https://github.com/surfstudio/surf-flutter-app-template#workflow-in-a-repository).
- [ ] The author is marked as an assigne and assigned mandatory reviewers.
- [ ] Required labels marked
- [ ] Specified related tasks and/or related PRs.
- [ ] Specified Changes.
- [ ] Attached videos/screenshots demonstrating the fix/feature.
- [ ] All unspecified fields in the PR description deleted.
- [ ] New code covered by tests.

## Checklist for reviewers
- [ ] CI passed successfully _(with a green check mark)_.
- [ ] PR is atomic, by volume no more than 400 (+-) corrected lines (not including codogen).

Design:
- [ ] System design corresponds to the agreements on structure and architecture on the project.
- [ ] The code is decomposed into necessary and sufficient components.

Functionality:
- [ ] The code solves the problem.
- [ ] Any changes to the user interface are reasonable and look good.

Complexity:
- [ ] The code is clear, easy to read, functions are small, no more than 50 lines.
- [ ] The logic is not overcomplicated, there is no overengineering (no code sections that may be needed in the future, but no one knows about it).

Tests:
- [ ] Updated or added tests for mandatory components.
- [ ] The tests are correct, helpful, and well designed/developed.

Naming:
- [ ] The naming of variables, methods, classes and other components is understandable.

Comments:
- [ ] The comments are understandable and helpful.

Documentation:
- [ ] All labels are correct
- [ ] Technical documentation updated (after approval, updates last reviewer).

2023-10-25 05:33 UTC, maxim-sysoev commented on lib/api/service/photos/dtos/photos_dto.dart
> +class PhotosDTO {
у другого DTO есть `@immutable`

2023-10-25 05:33 UTC, maxim-sysoev commented on lib/config/app_config.dart
> +    String? photosBaseUrl,
вместо этого свойства нельзя использовать url?

2023-10-25 05:33 UTC, maxim-sysoev commented on lib/features/app/di/app_scope.dart
> +            _themeByDefault;
интересно почему понадобилось переформатировать? какую длину строки используешь?

2023-10-25 05:33 UTC, maxim-sysoev commented on lib/features/photos/domain/entity/models/photos_model.dart
> +class PhotosModel {
`@immutable` чтобы показать что объект не может измениться

2023-10-25 05:33 UTC, maxim-sysoev commented on lib/features/photos/screens/photos_screen/photos_screen.dart
> +          );
повторяется в 3-х местах, нужно переиспользовать или задать в одном месте

2023-10-25 05:33 UTC, maxim-sysoev commented on lib/features/photos/screens/photos_screen/photos_screen.dart
> +    return Center(
точно нужен `Center`?

2023-10-25 05:33 UTC, maxim-sysoev commented on lib/features/photos/screens/photos_screen/photos_screen.dart
> +          SliverFillRemaining(
добавь свойство `hasScrollBody: false` чтобы контент занял только место до конца страницы и не добавлял скролл к списку

2023-10-25 05:33 UTC, maxim-sysoev commented on lib/features/photos/screens/photos_screen/photos_screen_widget_model.dart
> +  final networkErrorMessage = context.l10n.networkErrorMessage;
это лучше использовать на ui.
Обычно делаем унифицированный экран для обработки ошибок, в который просто передаём исключение. А он дальше внутри распарсит ошибку и покажет необходимое сообщение

2023-10-25 05:33 UTC, maxim-sysoev commented on lib/features/photos/screens/photos_screen/photos_screen_widget_model.dart
> +    extends WidgetModel<PhotosScreen, PhotosScreenModel>
что-то с длиной строки стало

2023-10-25 05:33 UTC, maxim-sysoev commented on lib/features/photos/screens/photos_screen/photos_screen_widget_model.dart
> +    super.initWidgetModel();
сначала вызывается метод инициализации wm, только после этого можено делать какие-то свои действия

2023-10-25 05:33 UTC, maxim-sysoev commented on lib/features/photos/widgets/photos_grid.dart
> +          return null;
если что-то сделанно временно - стоит добавлять todo для упрощения понимания другими разработчиками, что тут планируются изменения и можно не трогать.

2023-10-25 06:41 UTC, NKom-17 commented on lib/features/app/di/app_scope.dart
> +            _themeByDefault;
100

2023-10-25 06:46 UTC, NKom-17 commented on lib/config/app_config.dart
> +    String? photosBaseUrl,
можно наверно

2023-10-25 09:47 UTC, maxim-sysoev commented on lib/features/app/di/app_scope.dart
> +            _themeByDefault;
сделай отдельный ПР в main после вызова `fvm dart format -l 100 .`

2023-10-25 09:47 UTC, maxim-sysoev commented on lib/config/app_config.dart
> +    String? photosBaseUrl,
стоит сделать

2023-10-25 09:56 UTC, maxim-sysoev commented on lib/features/photos/screens/photos_screen/photos_screen_model.dart
> +      response.isNotEmpty ? dataState.content(response) : dataState.failure();
точно должна быть ошибка, если список пуст? 
кажется в таком случае нужно отключать дозагрузку просто, т.к. контент закончился

2023-10-25 09:56 UTC, maxim-sysoev commented on lib/features/photos/screens/photos_screen/photos_screen_widget_model.dart
> +  // final networkErrorMessage = context.l10n.networkErrorMessage;
такое нужно удалять

2023-10-25 09:56 UTC, maxim-sysoev commented on lib/features/photos/screens/photos_screen/photos_screen.dart
> +          });
эта обработка должна происходить в wm

2023-10-25 09:56 UTC, maxim-sysoev commented on lib/features/photos/screens/photos_screen/photos_screen.dart
> +          return _BuilderView(lastData);
как выглядит контент с ошибкой?

2023-10-25 10:16 UTC, NKom-17 commented on lib/features/photos/screens/photos_screen/photos_screen.dart
> +          return _BuilderView(lastData);
![screen](https://github.com/NKom-17/surf-flutter-app-template/assets/133796364/cc34f7ce-6a25-4118-8671-b52d4fb0ebdd)

2023-10-25 10:18 UTC, NKom-17 commented on lib/features/photos/screens/photos_screen/photos_screen.dart
> +          return _BuilderView(lastData);
в этой ветке у меня еще нет подгрузки новой страницы, поэтому чтобы проверить ошибку я вручную перезагружал без интернета и данных нет

2023-10-26 06:55 UTC, maxim-sysoev commented on lib/features/photos/screens/photos_screen/photos_screen_widget_model.dart
> +    WidgetsBinding.instance.addPostFrameCallback((_) {
точно нужен `WidgetsBinding.instance.addPostFrameCallback`?

2023-10-26 06:55 UTC, maxim-sysoev commented on lib/features/photos/screens/photos_screen/photos_screen_widget_model.dart
> +  void showErrorSnackBar(Exception? exception) {}
вряд ли нужен этот метод на ui

2023-10-26 09:37 UTC, maxim-sysoev requested changes

2023-10-26 09:37 UTC, maxim-sysoev commented on lib/features/photos/screens/photos_screen/photos_screen.dart
> +final scaffoldKey = GlobalKey<ScaffoldState>();
это должно быть в wm
не создаём глабальные переменные без реальной на то необходимости. В данном случае её нет.
Глобальные переменные хоть и заполнятся только после обращения, но будут жить всё оставшееся время жизни приложения, что не круто.
В сравнении локальные wm очищаются после диспоуза wm

2023-10-26 09:37 UTC, maxim-sysoev commented on lib/features/photos/screens/photos_screen/photos_screen.dart
> +                child: Visibility(
может не добавлять в скролл элемент, если он не нужен?
не вижу причин добавлять Visibility

2023-10-26 09:37 UTC, maxim-sysoev commented on test/core/utils/test_widget.dart
> +typedef TestFunctionWithTheme = Future<dynamic> Function(WidgetTester, ThemeData);
не используем dynamic. Анализатор должен был выругнуться на это

2023-10-26 10:53 UTC, maxim-sysoev commented on lib/features/photos/screens/photos_screen/photos_screen_model.dart
> +        return e.error as Exception?;
стоит спользовать rethrow;
`e.error as Exception?` - не стоит делать таких операций, если нет уверенности в типе переменной. Сейчас я так понимаю в error другой тип

возвращать ошибку в целом не очень хорошо, лучше её отловить через catch в wm

2023-10-26 14:10 UTC, maxim-sysoev approved these changes

2023-10-26 14:11 UTC, merged